import { createClient } from "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.57.4/+esm";
import { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY } from "./config.js";
const supabase=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);const $=s=>document.querySelector(s),esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));let signUpMode=false,currentUser=null,cases=[];
const authModal=$("#authModal"),caseModal=$("#caseModal");function openModal(x){x.classList.remove("hidden")}function closeModal(x){x.classList.add("hidden")}function notice(x,m,e=false){x.textContent=m;x.className="notice "+(e?"error":"")}
["openAuth","heroAuth","ctaAuth"].forEach(id=>$("#"+id).onclick=()=>openModal(authModal));document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>closeModal($("#"+b.dataset.close)));
$("#toggleAuth").onclick=()=>{signUpMode=!signUpMode;$("#authSubmit").textContent=signUpMode?"Create account":"Sign in";$("#toggleAuth").textContent=signUpMode?"Already have an account? Sign in":"Need an account? Create one";$("#authTitle").textContent=signUpMode?"Create your RecoverDesk account":"Enter RecoverDesk"};
$("#authForm").onsubmit=async e=>{e.preventDefault();notice($("#authMessage"),"Working…");const email=$("#authEmail").value.trim(),password=$("#authPassword").value;const r=signUpMode?await supabase.auth.signUp({email,password}):await supabase.auth.signInWithPassword({email,password});if(r.error)return notice($("#authMessage"),r.error.message,true);if(signUpMode&&!r.data.session)return notice($("#authMessage"),"Account created. Check your email to confirm access.");closeModal(authModal)};
async function loadCases(){if(!currentUser)return;const {data,error}=await supabase.from("recovery_cases").select("*").eq("owner_id",currentUser.id).order("created_at",{ascending:false});if(error)return console.error(error);cases=data||[];renderWorkspace()}
function renderWorkspace(){document.body.classList.add("in-app");document.querySelector("main").innerHTML='<section class="container app-shell" id="workspace"><aside class="sidebar"><div class="brand"><span class="brand-mark">R</span><span>RecoverDesk</span></div><div class="side-note">Recovery operations</div><button class="side-btn active" data-view="cases">Cases</button><button class="side-btn" data-view="activity">Activity</button><div class="side-bottom"><small>'+esc(currentUser.email)+'</small><button class="text-btn" id="signOut">Sign out</button></div></aside><section class="app-main"><div class="app-top"><div><div class="eyebrow">WORKSPACE</div><h1>Recovery desk</h1></div><button class="btn btn-primary" id="newCase">New case</button></div><div id="view"></div></section></section>';bindWorkspace();renderView("cases")}
function bindWorkspace(){$("#newCase").onclick=()=>{notice($("#caseMessage"),"");openModal(caseModal)};$("#signOut").onclick=async()=>{await supabase.auth.signOut();location.reload()};document.querySelectorAll(".side-btn").forEach(b=>b.onclick=()=>{document.querySelectorAll(".side-btn").forEach(x=>x.classList.remove("active"));b.classList.add("active");renderView(b.dataset.view)})}
function renderView(view){const v=$("#view");if(view==="activity"){v.innerHTML='<div class="panel"><h3>Recent activity</h3><div id="activityList">Loading…</div></div>';loadActivity();return}const open=cases.filter(c=>c.status==="open").length,prog=cases.filter(c=>c.status==="in_progress").length,urgent=cases.filter(c=>c.priority==="urgent").length,res=cases.filter(c=>["resolved","closed"].includes(c.status)).length;v.innerHTML='<div class="stats"><div><span>Open</span><strong>'+open+'</strong></div><div><span>In progress</span><strong>'+prog+'</strong></div><div><span>Urgent</span><strong>'+urgent+'</strong></div><div><span>Resolved</span><strong>'+res+'</strong></div></div><div class="panel"><div class="panel-head"><h3>Cases</h3><span>'+cases.length+' total</span></div><div class="case-list">'+(cases.length?cases.map(caseCard).join(""):'<div class="empty">No recovery cases yet. Create the first one.</div>')+'</div></div>';v.querySelectorAll("[data-status]").forEach(b=>b.onclick=()=>updateStatus(b.dataset.id,b.dataset.status))}
function caseCard(c){const next={open:"in_progress",in_progress:"resolved",resolved:"closed",closed:"open"}[c.status];return '<article class="case"><div class="case-main"><div class="case-meta"><span class="pill '+esc(c.priority)+'">'+esc(c.priority)+'</span><span>'+esc(c.status.replace("_"," "))+'</span></div><h3>'+esc(c.title)+'</h3><p>'+esc(c.description||"No description")+'</p><small>'+new Date(c.created_at).toLocaleString()+(c.source?" · "+esc(c.source):"")+'</small></div><button class="btn btn-small" data-id="'+c.id+'" data-status="'+next+'">'+(next==="in_progress"?"Start":next==="resolved"?"Resolve":next==="closed"?"Close":"Reopen")+'</button></article>'}
async function updateStatus(id,status){const {error}=await supabase.from("recovery_cases").update({status,updated_at:new Date().toISOString(),resolved_at:["resolved","closed"].includes(status)?new Date().toISOString():null}).eq("id",id).eq("owner_id",currentUser.id);if(error)return console.error(error);await supabase.from("case_events").insert({case_id:id,actor_id:currentUser.id,event_type:"status_changed",message:"Status changed to "+status,metadata:{status}});await loadCases()}
$("#caseForm").onsubmit=async e=>{e.preventDefault();notice($("#caseMessage"),"Creating…");const payload={owner_id:currentUser.id,title:$("#caseTitle").value.trim(),description:$("#caseDescription").value.trim()||null,priority:$("#casePriority").value,source:$("#caseSource").value.trim()||null,due_at:$("#caseDue").value?new Date($("#caseDue").value).toISOString():null};const {data,error}=await supabase.from("recovery_cases").insert(payload).select().single();if(error)return notice($("#caseMessage"),error.message,true);await supabase.from("case_events").insert({case_id:data.id,actor_id:currentUser.id,event_type:"case_created",message:"Case created",metadata:{priority:data.priority}});e.target.reset();closeModal(caseModal);await loadCases()}
async function loadActivity(){const {data,error}=await supabase.from("case_events").select("id,event_type,message,created_at,metadata,recovery_cases!inner(title,owner_id)").eq("recovery_cases.owner_id",currentUser.id).order("created_at",{ascending:false}).limit(50);$("#activityList").innerHTML=error?'<div class="empty">Could not load activity.</div>':data?.length?data.map(x=>'<div class="activity"><b>'+esc(x.event_type.replaceAll("_"," "))+'</b><span>'+esc(x.recovery_cases.title)+'</span><small>'+esc(x.message||"")+' · '+new Date(x.created_at).toLocaleString()+'</small></div>').join(""):'<div class="empty">No activity yet.</div>'}
supabase.auth.onAuthStateChange(async(_event,session)=>{currentUser=session?.user||null;if(currentUser){closeModal(authModal);await loadCases()}});const {data:{session}}=await supabase.auth.getSession();if(session){currentUser=session.user;await loadCases()}
